package application.gui.administrator.controller;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import application.gui.controller.BaseController;
import javafx.event.ActionEvent;

import javafx.scene.control.ChoiceBox;

import javafx.scene.control.TableColumn;

public class DodajNalogController extends BaseController{
	@FXML
	private TableColumn kolonaJmbg;
	@FXML
	private TableColumn kolonaIme;
	@FXML
	private TableColumn kolonaPrezime;
	@FXML
	private ChoiceBox ulogaChoiceBox;
	@FXML
	private TextField korisnickoIme;

	// Event Listener on Button.onAction
	@FXML
	public void dodajteNalogKlik(ActionEvent event) {
		// TODO Autogenerated
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		// TODO Auto-generated method stub
		
	}
}
