package application.gui.administrator.controller;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class PromjenaLozinkeController {
	@FXML
	private PasswordField lozinkaTxt;
	@FXML
	private PasswordField lozinkaPonovoTxt;

	// Event Listener on Button.onAction
	@FXML
	public void dugmeOkKlik(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void dugmeCancelKlik(ActionEvent event) {
		// TODO Autogenerated
	}
}
