package application.gui.sekretar.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.control.ToggleGroup;
import application.model.dto.ZaposleniDTO;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.RadioButton;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class RadSaZaposlenimaController {
	@FXML
	private ComboBox<String> cbFilter;
	@FXML
	private TextField txtFilter;
	@FXML
	private TableView<ZaposleniDTO> tblZaposleni;
	@FXML
	private TableColumn<ZaposleniDTO, String> colIme;
	@FXML
	private TableColumn<ZaposleniDTO, String> colImeRoditelja;
	@FXML
	private TableColumn colPrezime;
	@FXML
	private TableColumn colJMB;
	@FXML
	private TableColumn colDatumRodjenja;
	@FXML
	private TableColumn colRadnoMjesto;
	@FXML
	private TableColumn colAktivan;
	@FXML
	private Button btnAzuriraj;
	@FXML
	private Button btnObrisi;
	@FXML
	private RadioButton rbZaposleni;
	@FXML
	private ToggleGroup grpZaposleni;
	@FXML
	private RadioButton rbNezaposleni;
	@FXML
	private RadioButton rbSvi;
	@FXML
	private Button btnDodaj;
	@FXML
	private Button btnPretraga;
	@FXML
	private Button btnDodajZaposlenje;
	@FXML
	private Button btnDetalji;

	// Event Listener on Button[#btnAzuriraj].onAction
	@FXML
	public void azuriraj(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnObrisi].onAction
	@FXML
	public void obrisi(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on RadioButton[#rbZaposleni].onAction
	@FXML
	public void prikaziZaposlene(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on RadioButton[#rbNezaposleni].onAction
	@FXML
	public void prikaziNezaposlene(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on RadioButton[#rbSvi].onAction
	@FXML
	public void prikaziSve(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDodaj].onAction
	@FXML
	public void dodajZaposlenog(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnPretraga].onAction
	@FXML
	public void pretrazi(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDodajZaposlenje].onAction
	@FXML
	public void dodajZaposlenje(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDetalji].onAction
	@FXML
	public void prikaziDetalje(ActionEvent event) {
		// TODO Autogenerated
	}
}
