package application.gui.sekretar.controller;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import application.gui.controller.BaseController;
import application.model.dto.UgovorDTO;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.event.EventType;
import javafx.scene.control.ComboBox;

import javafx.scene.control.TextArea;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.control.TableView;

import javafx.scene.control.DatePicker;

import javafx.scene.control.TableColumn;

public class RadSaUgovorimaController extends BaseController{
	@FXML
	private TableView<UgovorDTO> tblUgovori;
	@FXML
	private TableColumn<UgovorDTO, Integer> colRb;
	@FXML
	private TableColumn<UgovorDTO, String> colDatumOd;
	@FXML
	private TableColumn<UgovorDTO, String> colDatumDo;
	@FXML
	private TableColumn<UgovorDTO, String> colSaDonacijom;
	@FXML
	private ComboBox<String> cbTip;
	@FXML
	private DatePicker dpDatumOd;
	@FXML
	private DatePicker dpDatumDo;
	@FXML
	private Button btnPretrazi;
	@FXML
	private TextArea taOpis;
	@FXML
	private Button btnPregledajDonacije;

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		colRb.setCellValueFactory(new PropertyValueFactory<UgovorDTO, Integer>("redniBroj"));
		colDatumOd.setCellValueFactory(new PropertyValueFactory<UgovorDTO, String>("datumOd"));
		colDatumDo.setCellValueFactory(new PropertyValueFactory<UgovorDTO, String>("datumDo"));
		colSaDonacijom.setCellValueFactory(new PropertyValueFactory<UgovorDTO, String>("saDonacijom"));
		cbTip.setItems(cbItems);
		cbTip.getSelectionModel().select(0);
		btnPregledajDonacije.disableProperty().bind(tblUgovori.getSelectionModel().selectedItemProperty().isNull());
	}
	
	// Event Listener on ComboBox[#cbTip].onAction
	@FXML
	public void filtriraj(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnPretrazi].onAction
	@FXML
	public void pretrazi(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnPregledajDonacije].onAction
	@FXML
	public void pregledajDonacije(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void setListaUgovora(ObservableList<UgovorDTO> listaUgovora){
		this.listaUgovora = listaUgovora;
		tblUgovori.setItems(listaUgovora);
	}
	
	@FXML
	public void updateOpis(){
		System.out.println("HERE");
		UgovorDTO ugovorDTO = tblUgovori.getSelectionModel().getSelectedItem();
		if(ugovorDTO != null){
			taOpis.setText(ugovorDTO.getOpis());
		}
	}
	@FXML
	public void deselect() {
		tblUgovori.getSelectionModel().clearSelection();
		taOpis.setText("");
	}
	private ObservableList<UgovorDTO> listaUgovora;
	private static ObservableList<String> cbItems = FXCollections.observableArrayList();
	static{
		cbItems.add("Svi");
		cbItems.add("Bez donacija");
		cbItems.add("Sa donacijama");
	}
	
}
